#!/usr/bin/expect

# Select planet Mercury 199, Venus 299, etc (not Earth)
# set OBJECT 899
# Planet number must be passed when expect_horizon is called 
# e.g. ./expect_horizon 899
set OBJECT [lindex $argv 0]

#Select place to observe from
# set COORD_CENTER 500@799
set COORD_CENTER [lindex $argv 1]

# Set start and end date for data
# set START "2022-August-07 00:00"
# set END "2023-August-24 00:00"
set START [lindex $argv 2]
set END [lindex $argv 3]

# interval between readings
set INTERVAL [lindex $argv 4]

set timeout 5
spawn telnet horizons.jpl.nasa.gov 6775

expect "Horizons> "
send -- "$OBJECT\n"

expect "Select"
send -- "e\n"

expect "Observe"
send -- "v\n"

expect "Coordinate"
send -- "$COORD_CENTER\n"

expect "Confirm"
send -- "y\n"

expect "Reference"
send -- "f\n"

expect "Starting"
send -- "${START}"

expect "Ending"
send -- "${END}"

expect "Output"
send -- "$INTERVAL"

expect "Accept"
send -- "n\n"

expect "Output"
send -- "\n"

expect "Corrections"
send -- "\n"

expect "Output"
send -- "\n"

expect "Spreadsheet"
send -- "y\n"

expect "Output"
send -- "\n"

expect "Select"
send -- "\n"

expect ""
send -- "q\n"

expect ">>> Select..."
send -- "f\n"

expect "File name   :  "
expect "\n"
set file [open "data/ephemeris_file_name.txt" w]
puts $file $expect_out(buffer)
close $file

expect ">>> Select..."
send -- "x\n"

expect eof